name: remember.yml
on:
  schedule:
    - cron: '0 15 * * *'
jobs:
  remember:
    environment: remember-env
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          version: 'latest'
          enable-cache: true
          cache-dependency-glob: 'uv.lock'


      - name: Install the dependencies
        run: uv sync --no-dev

      - name: Run the script
        run: uv run main.py
        env:
          POSTMARK_SERVER_API_TOKEN: ${{ secrets.POSTMARK_SERVER_API_TOKEN }}
          RECEIVER_MAIL: ${{ vars.RECEIVER_MAIL }}
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
          MISTRAL_MODEL: ${{ mistral-large-latest }}
